# Generated by Django 5.2.7 on 2025-10-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
